config/routes.rb
MiniBlog::Application.routes.draw do
  get "sessions/new"
  get 'sign-up', to:'authors#new', as: :signup
  get 'sign-in', to:'sessions#new', as: :signin
  delete 'sign-out', to: 'sessions#destroy', as: :signout

  resources :posts do
    resources :comments
  end
  
  resources :comments
  resources :sessions
  resources :authors

  get "home/index"

  root :to => 'home#index'

  

  

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :comments, through: :posts
  attr_accessible :bio, :email, :first_name, :last_name, :twitter, :username, :password, :password_confirmation
  validates :first_name, :last_name, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :bio, length: { in: 10..500 }

  validates :email, presence: true,
                    uniqueness: true,
                    length: { minimum: 3 },
                    format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/}

  def full_name 
    (first_name + " " + last_name).titleize
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authorize, only: [:update, :destroy, :edit]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for @author do |f| %>

  <%= f.error_notification %>
  
  <%= f.input :first_name, placeholder: "Your First Name" %>
  <%= f.input :last_name, placeholder: "Your Last Name" %>
  <%= f.input :username, placeholder: "Pick a Username" %>
  <%= f.input :bio, placeholder: "Tell us about yourself" %>
  <%= f.input :email, placeholder: "email@example.com" %>
  <%= f.input :twitter, placeholder: "@twitterhandle" %>
  <%= f.input :password, placeholder: "Password" %>
  <%= f.input :password_confirmation, placeholder: "Confirm Password" %>
  <%= f.button :submit %>

<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>All my Sweet Authors</h1>



<% @authors.each do |author| %>
    <h2><%= author.first_name %> <%= author.last_name %> (<%= link_to author.username, author_path(author) %>)</h2>
    <p><%= author.bio %></p>
    <%= mail_to author.email %>
    <%= link_to author.twitter, "http://www.twitter.com/"+author.twitter %>
    

<%= link_to 'Edit', edit_author_path(author) %>
<%= link_to 'Delete', author, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Show', author %>


<% end %>




<br /> 

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @author.full_name %></h1>


<p>
  <b>Username:</b>
  <%= @author.username %>
</p>

<p>
  <b>Bio:</b>
  <%= @author.bio %>
</p>

<p>
  <b>Email:</b>
  <%= mail_to @author.email %>
</p>

<p>
  <b>Twitter:</b>
  <%= link_to @author.twitter, "http://www.twitter.com/"+@author.twitter %>
</p>
<%= link_to 'Edit Profile', edit_author_path(@author) %> 

<hr />

<!-- So this part up here ^ is for the Author. This part down here v is all of his posts. These are separate by design.  -->

<h3> <%= @author.first_name%>'s posts</h3>
  <% @author.posts.each do |post| %>
  <h2><%= link_to post.title.titleize, post %></h2>
  <h4><%= time_tag(post.publish_at.to_date) %></h4>
  <p><%= simple_format(truncate(post.body, length: 140)) %></p>
<% end %>

<%= link_to 'Back', authors_path %>