config/routes.rb
MiniBlog::Application.routes.draw do
  get "sessions/new"
  get 'sign-up', to:'authors#new', as: :signup
  get 'sign-in', to:'sessions#new', as: :signin
  delete 'sign-out', to: 'sessions#destroy', as: :signout

  resources :posts do
    resources :comments
  end
  
  resources :comments
  resources :sessions
  resources :authors

  get "home/index"

  root :to => 'home#index'

  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author
  has_many :comments, dependent: :destroy
  attr_accessible :body, :publish_at, :title, :author_id
  validates :body, length: { in: 10..10000 }
  validates :title, presence: true
  validates :author, presence: {message: "must be a real author that exists, don't hack me"}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, only: [:new, :create, :update, :destroy, :edit]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where("publish_at <=  ?", Time.now).order("publish_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new

    @post = current_author.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    
    @post = current_author.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :publish_at %>
  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>All my Sweet Posts <small> (<%= @posts.count %>) </small></h1>



<% @posts.each do |post| %>
<h2><%= link_to post.title.titleize, post %></h2>
<h4><%= time_tag(post.publish_at.to_date) %></h4>
<p><%= simple_format(truncate(post.body, length: 140)) %></p>
  
<%= link_to 'Edit', edit_post_path(post) %>
<%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>



<% end %>
<br/>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @post.title.titleize %></h2>
<h3><%= link_to(@post.author.try(:username), author_path(@post.author)) %></h3>
<h4><%= time_tag(@post.publish_at.to_date) %></h4>
<p><%= simple_format(@post.body) %></p>

<h3> Comments</h3>
<% @post.comments.each do |comment| %>
  <h4><%= comment.commenter_name %></h4>
  <p><%= simple_format(comment.message) %></p>
<% end %>

<%= form_for(@comments) do |f| %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :commenter_name %><br />
    <%= f.text_field :commenter_name %>
  </div>
  <div class="field">
    <%= f.hidden_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>